name: career_public_school
version: 1.0.0+1
publish_to: none
description: A new Flutter project for career public school.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/cps_light.png"

